name: Check for updates
on:
  schedule: 
  - cron: "0 * * * *" 
  workflow_dispatch: 

permissions:
  contents: write
  pull-requests: write

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [ main ] # list all branches to check
    
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ matrix.branch }}
      - name: Set variables
        id: variables
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update -y
          git config --global protocol.file.allow always
          sudo apt-get install --no-install-recommends -y python3
          echo "APP_NAME=$(basename $(git rev-parse --show-toplevel))" >> $GITHUB_OUTPUT
          python3 scripts/versions.py
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.EXTERNAL_DATA_SECRET }}
        with:
          args: --update --never-fork ${{ steps.variables.outputs.APP_NAME }}.yml
